filebeat:
  inputs:
    - type: log
      paths:
        - /var/log/service.log

output.kafka:
  hosts: ["localhost:9092"]
  topic: 'log'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
