version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: ./build/libs/zazazan-0.0.1-SNAPSHOT.jar
#    image:
    ports:
      - "8088:8088"

  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kakfa-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.0
    container_name: filebeat
    volumes:
      - "./docker/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/log:/var/log"
    depends_on:
      - kafka
